app:
  router:
    swagger_ui: /
    version_ui: 3
  resources:
    /status:
      get: handlers.status
  # Custom access log class
  access_log_class: access_log_class.DebugAccessLogClass
#  access_log_format: '%a %t %s'

status:
  data: 1
