http:
  # Custom access log class
  access_log:
    cls: access_log_class.DebugAccessLogClass
    format: '%a %t %s'


app:
  router:
    swagger_ui: /
    version_ui: 3
  resources:
    /status:
      get: handlers.status

status:
  data: 1
