dist: xenial
language: python
sudo: false
python:
- 3.5.3
- '3.6'
- '3.7'
install:
- pip install -U pip setuptools
- pip install -U pipenv codecov
- pipenv install -d --skip-lock --system
- pip install -e .
script: pytest --cov=aioworkers_aiohttp
after_success:
- codecov
before_deploy:
- echo "__version__ = '$(git describe --tags)'" > aioworkers_aiohttp/version.py
deploy:
  provider: pypi
  user: yttrium
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
  skip_cleanup: true
  password:
    secure: jiDfA2TRlSe3AocmXuu6Irfw8BFAj9DhHke3QIZX+LPf+sR5lxwcYoiJ2DhcA5Ixly1KVDQUS/CRFERst2xqPf5w8Fd7/+xmWahezIfdSfKxJr/6M/XMEoYtOUcdQC5qfeU0MUEhkAmewQL5GBQ1lHLBoqs9zMvwDaBJQU7WP1mz8ijf9QGmYGEOFcf78Phta+/m+1kCSNzTAgVTjcjJYSH8h3tnxTjDAdNAoBzB4kWibTkfyQk55QQW+qRO4pUljTwsrwp91RYvx1PDQq65pZBsaO8pTGpYHRVt35/uJCzemUHuuwM7AE1OpGwjBX0dJLqrs4VBWOgD8cRITYTUl6KKANLQTqphz7vvFVc5+En9z0O/xHICPCSyc2VrtOJ8C9bZtkhoQ5vgqeT4PfCgEszJGbCoTHjZHOttpIrIXW22x8kM+KMYHsrZl339UJSrFPYTeSD5vloJKcBznXaqSif2x1g+7DbvYcg6JguV0LPYO5tg1SssQtnautE+3DovTy2hMT66rUhLp0BHpcKBt9RF3HQhy+o5OyShkbcWebQS+gzooXQxFVXSPA8r0M6JBwIdhYi6oxWISMYVfgHAw/u9pm3/RTpMXp1kLdOplBXwwrCiKtjwmAVsxn4aUmdOr/CSI4TZBVhThsIAMURKU/GxEZd5C2vQF1yYJDK8kJ4=
