language: python
sudo: false
services: []
python:
  - 3.5.3
  - 3.6
#  - pypy3
install:
  - pip install -U pip setuptools
  - pip install -U pytest-runner pytest-aiohttp pytest-pep8 pytest-mock pytest-cov
  - pip install -U aiohttp aiohttp_apiset
  - pip install codecov
  - python setup.py install
script: pytest --cov=aioworkers_aiohttp

after_success:
  - codecov
